server:
  applicationConnectors:
    - type: http
      port: 9090
logging:
  loggers:
    "datomic.db": WARN
  appenders:
    - type: console
      logFormat: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
jerseyClient:
  gzipEnabledForRequests: false
feedServerUrl: http://localhost:8080/folkeregister/person